### ISSUE TITLE
Fully qualified URL addition

### ISSUE THREAD

**Issue by RMHogervorst** [DavisVaughan/extrachecks#10]
I had the same issue on CRAN. 

```  
Found the following (possibly) invalid file URI:
     URI: CODE_OF_CONDUCT.md
       From: README.md
```
I mean this works on github, but it will probably break on CRAN.

**Comment by RMHogervorst** [comment]
nope I was just careless copying it. usethis adds a nice fully qualified url to https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html.

**Comment by DavisVaughan** [comment]
What did you do to fix this? I would probably link to the actual github page, like `https://github.com/tidymodels/recipes/blob/master/CODE_OF_CONDUCT.md`, rather than using relative path links.

Part of the problem might be that, for recipes at least, we `.Rbuildignore` the code of conduct file
https://github.com/tidymodels/recipes/blob/1490ff7b3bdefadc372d973f8d1f1a775e721b38/.Rbuildignore#L19

In the README of recipes at the very bottom you can see our contributing section. We link out to the actual code of conduct website where we pulled this from, rather than linking to the `CODE_OF_CONDUCT.md` file directly. So that's another option. https://raw.githubusercontent.com/tidymodels/recipes/master/README.md

**Comment by RMHogervorst** [comment]
My action was to link to the pkgdown website version of the CoC. Later I found that usethis links to the code of conduct website. That makes more sense I think.

**Comment by DavisVaughan** [comment]
In your `.Rbuildignore` did you have `CODE_OF_CONDUCT.md` as being ignored? If so, then that was probably the reason that this note was triggered (i.e. it was caught correctly on their end, even if it is a hidden check).

If you didn't have it as being ignored, then we probably can't do relative links in the readme, so I'd document the check differently

**Comment by RMHogervorst** [comment]
Yes CODE_OF_CONDUCT.md is in my .Rbuildignore.
